config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :todos, only: [:new, :create, :edit, :update, :destroy]
  end
  root to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :user
  enum status: [:to_do, :doing, :done]

  validates_presence_of :name, :status
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todos, dependent: :destroy

  validates_presence_of :name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[edit update destroy]
  before_action :set_user

  def new
    @todo = Todo.new
  end

  def edit; end

  def create
    @todo = Todo.new(todo_params)
    @todo.user = @user
    if @todo.save
      redirect_to user_path(@user), notice: 'Todo was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @todo.update(todo_params)
      redirect_to user_path(@user), notice: 'Todo was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @todo.destroy
    redirect_to user_path(@user), notice: 'Todo was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
  
  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name, :status, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user), notice: 'User was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: 'User was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<%= simple_form_for([@user, @todo]) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.input :status do %>
      <%= form.select :status, options_for_select(Todo.statuses.map {|key, value| [key.titleize, Todo.statuses.key(value)]}, @todo.status) %>
    <% end %>
  </div>

  <div class="action-btn">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<div class="main-container">
  <div class="note-section">
    <h1>Editing Todo</h1>
    <div class="table-container">
      <%= render 'form', todo: @todo %>
    </div>
    <div class="action-btn">
      <%= link_to 'Back', user_path(@user) %>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<div class="main-container">
  <div class="note-section">
      <h1>New Todo</h1>
      <div class="table-container">
        <%= render 'form', todo: @todo %>
      </div>
      <div class="action-btn">
        <%= link_to 'Back', user_path(@user) %>
      </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="action-btn">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="main-container">
  <div class="note-section">
    <h1>Edit User</h1>
    <div class="table-container">
      <%= render 'form', user: @user %>
    </div>
    <div class="action-btn">
      <%= link_to 'Back', users_path %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='main-container'>
  <p id="notice"><%= notice %></p>
  <div class='note-section'>
    <h1 class='title'>Users</h1>
    <div class='table-container'>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Todos</th>
            <th colspan="3"></th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr class='user-tr'>
              <td><%= link_to user.name, user %></td>
              <td><%= user.todos.count %></td>
              <td></td>
              <td>
                <%= link_to edit_user_path(user) do %>
                  <i class="fa-solid fa-pen-to-square"></i>
                <% end %>
                <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="fa-solid fa-trash"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <br>
    <div class='action-btn'>
      <%= link_to 'New User', new_user_path %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main-container">
  <div class="note-section">
      <h1>New User</h1>
      <div class="table-container">
        <%= render 'form', user: @user %>
      </div>
      <div class="action-btn">
        <%= link_to 'Back', users_path %>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='main-container'>
  <p id="notice"><%= notice %></p>
  <div class='note-section'>
    <h1 class='title'><%= @user.name %></h1>
    <p><%= @user.email %></p>
    <div class="table-container">
      <div class='user-content'>
        <% if @user.todos.empty? %>
          <p>No Todos have been assigned to this user</p>
        <% else %>
          <table>
            <thead>
              <tr>
                <th></th>
                <th>Name</th>
                <th>Status</th>
                <th colspan="3"></th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @user.todos.each do |todo| %>
                <tr>
                  <td>
                    <% if todo.done? %>
                      <i class="fa-solid fa-circle-check"></i>
                    <% end %>
                  </td>
                  <td><%= todo.name %></td>
                  <td><%= todo.status.titleize %></td>
                  <td></td>
                  <td>
                    <%= link_to edit_user_todo_path(@user,todo) do %>
                      <i class="fa-solid fa-pen-to-square"></i>
                    <% end %>
                    <%= link_to user_todo_path(@user,todo), method: :delete, remote: true, data: { confirm: 'Are you sure?' } do %>
                      <i class="fa-solid fa-trash"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <%end %>
        <div class="action-btn">
          <%= link_to 'Add Todo', new_user_todo_path(@user) %>
        </div>
      </div>
      <div class="action-btn">
        <%= link_to 'Edit', edit_user_path(@user) %> |
        <%= link_to 'Back', users_path %>
      </div>
    </div>
  </div>
</div>